### ISSUE TITLE
Project Working? Still Alive?

### ISSUE THREAD

**Issue by lwvmobile** [sp5wwp/ledacs#1]
Hello, didn't know where else to put this, but I was interested in using this software, and I have been testing it out, but I am unsure of whether or not it works or not, as I can lock onto a EDACS system but I can't seem to tune to different channels nor does the decoder ever show me any information. 

I was just writing to see if this project is still alive, if it is in a working state, etc.

**Comment by lwvmobile** [comment]
Hey, just wanted to try to reach out to you one more time to ascertain the status of this software, alive, dead? I also wanted to let you know I was going to fork and modify this software. I'd love to hear back from you, and make sure that it was okay to do so.

**Comment by sp5wwp** [comment]
Totally dead :-) I'm working on the [M17 Project](https://m17project.org/) at the moment. Do whatever you like with the code. Cheers!
